language: python

python: 
  - "3.6"

install: 
  - pip install -r requirements.txt

services:
  - postgresql

before_script: 
  - psql -c "CREATE DATABASE weconnect;" -U postgres
  - psql -c "CREATE USER louis;" -U postgres

env: 
  - DATABASE_URL=postgresql://tibzy@localhost/weconnect SECRET_KEY=some_secret_value 
  - APP_SETTINGS=config.TestingConfig
  
#script to run tests
script:
  - nosetests tests.tests --with-coverage
  - coverage report
  # - coverage run --source='.' --omit='app/main/*'  manage.py test
  # - coverage report --omit='app/main/*'

#update coveralls on cchanges
after_success:
  - coveralls
